# Generated by Django 5.2.8 on 2025-12-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_ALX', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gdrive_file_id',
            field=models.CharField(blank=True, help_text='Google Drive file ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='gdrive_file_url',
            field=models.URLField(blank=True, help_text='Google Drive file URL', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original uploaded filename', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='gdrive_file_id',
            field=models.CharField(blank=True, help_text='Google Drive file ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='gdrive_file_url',
            field=models.URLField(blank=True, help_text='Google Drive file URL', null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original uploaded filename', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
