# Generated by Django 5.2.4 on 2025-08-15 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMS_ALX', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
